//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Giris.UrunServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UrunServiceReference.UrunlerServisSoap")]
    public interface UrunlerServisSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: Generating message contract since message UrunlerListesiRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrunlerListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Service_Giris.UrunServiceReference.UrunlerListesiResponse UrunlerListesi(Service_Giris.UrunServiceReference.UrunlerListesiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrunlerListesi", ReplyAction="*")]
        System.Threading.Tasks.Task<Service_Giris.UrunServiceReference.UrunlerListesiResponse> UrunlerListesiAsync(Service_Giris.UrunServiceReference.UrunlerListesiRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Kimlik : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kullaniciAdiField;
        
        private string parolaField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
                this.RaisePropertyChanged("KullaniciAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Parola {
            get {
                return this.parolaField;
            }
            set {
                this.parolaField = value;
                this.RaisePropertyChanged("Parola");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UrunDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int urunIDField;
        
        private string urunAdiField;
        
        private System.Nullable<int> tedarikciIDField;
        
        private System.Nullable<int> kategoriIDField;
        
        private string birimdekiMiktarField;
        
        private System.Nullable<decimal> fiyatField;
        
        private System.Nullable<short> stokField;
        
        private System.Nullable<short> yeniSatisField;
        
        private System.Nullable<short> enAzYenidenSatisMikatariField;
        
        private bool sonlandiField;
        
        private string urunResimUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UrunID {
            get {
                return this.urunIDField;
            }
            set {
                this.urunIDField = value;
                this.RaisePropertyChanged("UrunID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UrunAdi {
            get {
                return this.urunAdiField;
            }
            set {
                this.urunAdiField = value;
                this.RaisePropertyChanged("UrunAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> TedarikciID {
            get {
                return this.tedarikciIDField;
            }
            set {
                this.tedarikciIDField = value;
                this.RaisePropertyChanged("TedarikciID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> KategoriID {
            get {
                return this.kategoriIDField;
            }
            set {
                this.kategoriIDField = value;
                this.RaisePropertyChanged("KategoriID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BirimdekiMiktar {
            get {
                return this.birimdekiMiktarField;
            }
            set {
                this.birimdekiMiktarField = value;
                this.RaisePropertyChanged("BirimdekiMiktar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> Fiyat {
            get {
                return this.fiyatField;
            }
            set {
                this.fiyatField = value;
                this.RaisePropertyChanged("Fiyat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<short> Stok {
            get {
                return this.stokField;
            }
            set {
                this.stokField = value;
                this.RaisePropertyChanged("Stok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<short> YeniSatis {
            get {
                return this.yeniSatisField;
            }
            set {
                this.yeniSatisField = value;
                this.RaisePropertyChanged("YeniSatis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<short> EnAzYenidenSatisMikatari {
            get {
                return this.enAzYenidenSatisMikatariField;
            }
            set {
                this.enAzYenidenSatisMikatariField = value;
                this.RaisePropertyChanged("EnAzYenidenSatisMikatari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Sonlandi {
            get {
                return this.sonlandiField;
            }
            set {
                this.sonlandiField = value;
                this.RaisePropertyChanged("Sonlandi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UrunResimUrl {
            get {
                return this.urunResimUrlField;
            }
            set {
                this.urunResimUrlField = value;
                this.RaisePropertyChanged("UrunResimUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UrunlerListesi", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UrunlerListesiRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Service_Giris.UrunServiceReference.Kimlik Kimlik;
        
        public UrunlerListesiRequest() {
        }
        
        public UrunlerListesiRequest(Service_Giris.UrunServiceReference.Kimlik Kimlik) {
            this.Kimlik = Kimlik;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UrunlerListesiResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UrunlerListesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Service_Giris.UrunServiceReference.UrunDTO[] UrunlerListesiResult;
        
        public UrunlerListesiResponse() {
        }
        
        public UrunlerListesiResponse(Service_Giris.UrunServiceReference.UrunDTO[] UrunlerListesiResult) {
            this.UrunlerListesiResult = UrunlerListesiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UrunlerServisSoapChannel : Service_Giris.UrunServiceReference.UrunlerServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UrunlerServisSoapClient : System.ServiceModel.ClientBase<Service_Giris.UrunServiceReference.UrunlerServisSoap>, Service_Giris.UrunServiceReference.UrunlerServisSoap {
        
        public UrunlerServisSoapClient() {
        }
        
        public UrunlerServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UrunlerServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrunlerServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrunlerServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service_Giris.UrunServiceReference.UrunlerListesiResponse Service_Giris.UrunServiceReference.UrunlerServisSoap.UrunlerListesi(Service_Giris.UrunServiceReference.UrunlerListesiRequest request) {
            return base.Channel.UrunlerListesi(request);
        }
        
        public Service_Giris.UrunServiceReference.UrunDTO[] UrunlerListesi(Service_Giris.UrunServiceReference.Kimlik Kimlik) {
            Service_Giris.UrunServiceReference.UrunlerListesiRequest inValue = new Service_Giris.UrunServiceReference.UrunlerListesiRequest();
            inValue.Kimlik = Kimlik;
            Service_Giris.UrunServiceReference.UrunlerListesiResponse retVal = ((Service_Giris.UrunServiceReference.UrunlerServisSoap)(this)).UrunlerListesi(inValue);
            return retVal.UrunlerListesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Service_Giris.UrunServiceReference.UrunlerListesiResponse> Service_Giris.UrunServiceReference.UrunlerServisSoap.UrunlerListesiAsync(Service_Giris.UrunServiceReference.UrunlerListesiRequest request) {
            return base.Channel.UrunlerListesiAsync(request);
        }
        
        public System.Threading.Tasks.Task<Service_Giris.UrunServiceReference.UrunlerListesiResponse> UrunlerListesiAsync(Service_Giris.UrunServiceReference.Kimlik Kimlik) {
            Service_Giris.UrunServiceReference.UrunlerListesiRequest inValue = new Service_Giris.UrunServiceReference.UrunlerListesiRequest();
            inValue.Kimlik = Kimlik;
            return ((Service_Giris.UrunServiceReference.UrunlerServisSoap)(this)).UrunlerListesiAsync(inValue);
        }
    }
}
