//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTuket.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunDTO", Namespace="http://schemas.datacontract.org/2004/07/KuzeyYeli.DTO.Urun")]
    [System.SerializableAttribute()]
    public partial class UrunDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirimdekiMiktarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> EnAzYenidenSatisMikatariField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KategoriIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SonlandiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> StokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TedarikciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UrunIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunResimUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> YeniSatisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirimdekiMiktar {
            get {
                return this.BirimdekiMiktarField;
            }
            set {
                if ((object.ReferenceEquals(this.BirimdekiMiktarField, value) != true)) {
                    this.BirimdekiMiktarField = value;
                    this.RaisePropertyChanged("BirimdekiMiktar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> EnAzYenidenSatisMikatari {
            get {
                return this.EnAzYenidenSatisMikatariField;
            }
            set {
                if ((this.EnAzYenidenSatisMikatariField.Equals(value) != true)) {
                    this.EnAzYenidenSatisMikatariField = value;
                    this.RaisePropertyChanged("EnAzYenidenSatisMikatari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Fiyat {
            get {
                return this.FiyatField;
            }
            set {
                if ((this.FiyatField.Equals(value) != true)) {
                    this.FiyatField = value;
                    this.RaisePropertyChanged("Fiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KategoriID {
            get {
                return this.KategoriIDField;
            }
            set {
                if ((this.KategoriIDField.Equals(value) != true)) {
                    this.KategoriIDField = value;
                    this.RaisePropertyChanged("KategoriID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sonlandi {
            get {
                return this.SonlandiField;
            }
            set {
                if ((this.SonlandiField.Equals(value) != true)) {
                    this.SonlandiField = value;
                    this.RaisePropertyChanged("Sonlandi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Stok {
            get {
                return this.StokField;
            }
            set {
                if ((this.StokField.Equals(value) != true)) {
                    this.StokField = value;
                    this.RaisePropertyChanged("Stok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TedarikciID {
            get {
                return this.TedarikciIDField;
            }
            set {
                if ((this.TedarikciIDField.Equals(value) != true)) {
                    this.TedarikciIDField = value;
                    this.RaisePropertyChanged("TedarikciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunAdi {
            get {
                return this.UrunAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdiField, value) != true)) {
                    this.UrunAdiField = value;
                    this.RaisePropertyChanged("UrunAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UrunID {
            get {
                return this.UrunIDField;
            }
            set {
                if ((this.UrunIDField.Equals(value) != true)) {
                    this.UrunIDField = value;
                    this.RaisePropertyChanged("UrunID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunResimUrl {
            get {
                return this.UrunResimUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunResimUrlField, value) != true)) {
                    this.UrunResimUrlField = value;
                    this.RaisePropertyChanged("UrunResimUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> YeniSatis {
            get {
                return this.YeniSatisField;
            }
            set {
                if ((this.YeniSatisField.Equals(value) != true)) {
                    this.YeniSatisField = value;
                    this.RaisePropertyChanged("YeniSatis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUrunService")]
    public interface IUrunService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UrunDTO/Listele", ReplyAction="http://tempuri.org/IServiceBaseOf_UrunDTO/ListeleResponse")]
        WCFTuket.ServiceReference1.UrunDTO[] Listele();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UrunDTO/Listele", ReplyAction="http://tempuri.org/IServiceBaseOf_UrunDTO/ListeleResponse")]
        System.Threading.Tasks.Task<WCFTuket.ServiceReference1.UrunDTO[]> ListeleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UrunDTO/Ekle", ReplyAction="http://tempuri.org/IServiceBaseOf_UrunDTO/EkleResponse")]
        bool Ekle(WCFTuket.ServiceReference1.UrunDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UrunDTO/Ekle", ReplyAction="http://tempuri.org/IServiceBaseOf_UrunDTO/EkleResponse")]
        System.Threading.Tasks.Task<bool> EkleAsync(WCFTuket.ServiceReference1.UrunDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UrunDTO/Guncelle", ReplyAction="http://tempuri.org/IServiceBaseOf_UrunDTO/GuncelleResponse")]
        bool Guncelle(WCFTuket.ServiceReference1.UrunDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UrunDTO/Guncelle", ReplyAction="http://tempuri.org/IServiceBaseOf_UrunDTO/GuncelleResponse")]
        System.Threading.Tasks.Task<bool> GuncelleAsync(WCFTuket.ServiceReference1.UrunDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UrunDTO/Sil", ReplyAction="http://tempuri.org/IServiceBaseOf_UrunDTO/SilResponse")]
        bool Sil(WCFTuket.ServiceReference1.UrunDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_UrunDTO/Sil", ReplyAction="http://tempuri.org/IServiceBaseOf_UrunDTO/SilResponse")]
        System.Threading.Tasks.Task<bool> SilAsync(WCFTuket.ServiceReference1.UrunDTO entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUrunServiceChannel : WCFTuket.ServiceReference1.IUrunService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UrunServiceClient : System.ServiceModel.ClientBase<WCFTuket.ServiceReference1.IUrunService>, WCFTuket.ServiceReference1.IUrunService {
        
        public UrunServiceClient() {
        }
        
        public UrunServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UrunServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrunServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrunServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFTuket.ServiceReference1.UrunDTO[] Listele() {
            return base.Channel.Listele();
        }
        
        public System.Threading.Tasks.Task<WCFTuket.ServiceReference1.UrunDTO[]> ListeleAsync() {
            return base.Channel.ListeleAsync();
        }
        
        public bool Ekle(WCFTuket.ServiceReference1.UrunDTO entity) {
            return base.Channel.Ekle(entity);
        }
        
        public System.Threading.Tasks.Task<bool> EkleAsync(WCFTuket.ServiceReference1.UrunDTO entity) {
            return base.Channel.EkleAsync(entity);
        }
        
        public bool Guncelle(WCFTuket.ServiceReference1.UrunDTO entity) {
            return base.Channel.Guncelle(entity);
        }
        
        public System.Threading.Tasks.Task<bool> GuncelleAsync(WCFTuket.ServiceReference1.UrunDTO entity) {
            return base.Channel.GuncelleAsync(entity);
        }
        
        public bool Sil(WCFTuket.ServiceReference1.UrunDTO entity) {
            return base.Channel.Sil(entity);
        }
        
        public System.Threading.Tasks.Task<bool> SilAsync(WCFTuket.ServiceReference1.UrunDTO entity) {
            return base.Channel.SilAsync(entity);
        }
    }
}
