//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win_WebServices.UrunService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UrunService.UrunServiceSoap")]
    public interface UrunServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: Generating message contract since message TumunuListeleRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TumunuListele", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Win_WebServices.UrunService.TumunuListeleResponse TumunuListele(Win_WebServices.UrunService.TumunuListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TumunuListele", ReplyAction="*")]
        System.Threading.Tasks.Task<Win_WebServices.UrunService.TumunuListeleResponse> TumunuListeleAsync(Win_WebServices.UrunService.TumunuListeleRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Oturum : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kullaniciAdiField;
        
        private string parolaField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
                this.RaisePropertyChanged("KullaniciAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Parola {
            get {
                return this.parolaField;
            }
            set {
                this.parolaField = value;
                this.RaisePropertyChanged("Parola");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UrunResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int urunIDField;
        
        private string urunAdiField;
        
        private System.Nullable<decimal> fiyatField;
        
        private System.Nullable<short> stokField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UrunID {
            get {
                return this.urunIDField;
            }
            set {
                this.urunIDField = value;
                this.RaisePropertyChanged("UrunID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UrunAdi {
            get {
                return this.urunAdiField;
            }
            set {
                this.urunAdiField = value;
                this.RaisePropertyChanged("UrunAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> Fiyat {
            get {
                return this.fiyatField;
            }
            set {
                this.fiyatField = value;
                this.RaisePropertyChanged("Fiyat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<short> Stok {
            get {
                return this.stokField;
            }
            set {
                this.stokField = value;
                this.RaisePropertyChanged("Stok");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TumunuListele", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TumunuListeleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Win_WebServices.UrunService.Oturum Oturum;
        
        public TumunuListeleRequest() {
        }
        
        public TumunuListeleRequest(Win_WebServices.UrunService.Oturum Oturum) {
            this.Oturum = Oturum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TumunuListeleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TumunuListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Win_WebServices.UrunService.UrunResult[] TumunuListeleResult;
        
        public TumunuListeleResponse() {
        }
        
        public TumunuListeleResponse(Win_WebServices.UrunService.UrunResult[] TumunuListeleResult) {
            this.TumunuListeleResult = TumunuListeleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UrunServiceSoapChannel : Win_WebServices.UrunService.UrunServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UrunServiceSoapClient : System.ServiceModel.ClientBase<Win_WebServices.UrunService.UrunServiceSoap>, Win_WebServices.UrunService.UrunServiceSoap {
        
        public UrunServiceSoapClient() {
        }
        
        public UrunServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UrunServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrunServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrunServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Win_WebServices.UrunService.TumunuListeleResponse Win_WebServices.UrunService.UrunServiceSoap.TumunuListele(Win_WebServices.UrunService.TumunuListeleRequest request) {
            return base.Channel.TumunuListele(request);
        }
        
        public Win_WebServices.UrunService.UrunResult[] TumunuListele(Win_WebServices.UrunService.Oturum Oturum) {
            Win_WebServices.UrunService.TumunuListeleRequest inValue = new Win_WebServices.UrunService.TumunuListeleRequest();
            inValue.Oturum = Oturum;
            Win_WebServices.UrunService.TumunuListeleResponse retVal = ((Win_WebServices.UrunService.UrunServiceSoap)(this)).TumunuListele(inValue);
            return retVal.TumunuListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Win_WebServices.UrunService.TumunuListeleResponse> Win_WebServices.UrunService.UrunServiceSoap.TumunuListeleAsync(Win_WebServices.UrunService.TumunuListeleRequest request) {
            return base.Channel.TumunuListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Win_WebServices.UrunService.TumunuListeleResponse> TumunuListeleAsync(Win_WebServices.UrunService.Oturum Oturum) {
            Win_WebServices.UrunService.TumunuListeleRequest inValue = new Win_WebServices.UrunService.TumunuListeleRequest();
            inValue.Oturum = Oturum;
            return ((Win_WebServices.UrunService.UrunServiceSoap)(this)).TumunuListeleAsync(inValue);
        }
    }
}
