<?xml version="1.0" encoding="utf-8"?><Database Name="KuzeyYeli" Class="KuzeyYeliDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=KuzeyYeli;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KuzeyYeliConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Applications" Member="aspnet_Applications">
    <Type Name="aspnet_Application">
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Memberships" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Membership" />
      <Association Name="aspnet_Application_aspnet_Path" Member="aspnet_Paths" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Path" />
      <Association Name="aspnet_Application_aspnet_Role" Member="aspnet_Roles" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Role" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Users" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_User" />
    </Type>
  </Table>
  <Table Name="dbo.Urunler" Member="Urunlers">
    <Type Name="Urunler">
      <Column Name="UrunID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UrunAdi" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TedarikciID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KategoriID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BirimdekiMiktar" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Fiyat" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Stok" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="YeniSatis" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EnAzYenidenSatisMikatari" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Sonlandi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UrunResimUrl" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Urunler_SatisDetay" Member="SatisDetays" ThisKey="UrunID" OtherKey="UrunID" Type="SatisDetay" />
      <Association Name="Kategoriler_Urunler" Member="Kategoriler" ThisKey="KategoriID" OtherKey="KategoriID" Type="Kategoriler" IsForeignKey="true" />
      <Association Name="Tedarikciler_Urunler" Member="Tedarikciler" ThisKey="TedarikciID" OtherKey="TedarikciID" Type="Tedarikciler" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Memberships">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Paths" Member="aspnet_Paths">
    <Type Name="aspnet_Path">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredPath" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationAllUser" Member="aspnet_PersonalizationAllUser" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationAllUser" Cardinality="One" />
      <Association Name="aspnet_Path_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_Application_aspnet_Path" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationAllUsers" Member="aspnet_PersonalizationAllUsers">
    <Type Name="aspnet_PersonalizationAllUser">
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationAllUser" Member="aspnet_Path" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Path" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers">
    <Type Name="aspnet_PersonalizationPerUser">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationPerUser" Member="aspnet_Path" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Path" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_PersonalizationPerUser" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Profile" Member="aspnet_Profiles">
    <Type Name="aspnet_Profile">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PropertyNames" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesString" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesBinary" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Profile" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Roles" Member="aspnet_Roles">
    <Type Name="aspnet_Role">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_UsersInRole" />
      <Association Name="aspnet_Application_aspnet_Role" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_SchemaVersions" Member="aspnet_SchemaVersions">
    <Type Name="aspnet_SchemaVersion">
      <Column Name="Feature" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompatibleSchemaVersion" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsCurrentVersion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers" ThisKey="UserId" OtherKey="UserId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_User_aspnet_Profile" Member="aspnet_Profile" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Profile" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="aspnet_UsersInRole" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UsersInRoles" Member="aspnet_UsersInRoles">
    <Type Name="aspnet_UsersInRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_Role" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_Role" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_WebEvent_Events" Member="aspnet_WebEvent_Events">
    <Type Name="aspnet_WebEvent_Event">
      <Column Name="EventId" Type="System.String" DbType="Char(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="EventSequence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventOccurrence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventDetailCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ApplicationPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ApplicationVirtualPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="RequestUrl" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ExceptionType" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Bolge" Member="Bolges">
    <Type Name="Bolge">
      <Column Name="BolgeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BolgeTanimi" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Bolge_Bolgeler" Member="Bolgelers" ThisKey="BolgeID" OtherKey="BolgeID" Type="Bolgeler" />
    </Type>
  </Table>
  <Table Name="dbo.Bolgeler" Member="Bolgelers">
    <Type Name="Bolgeler">
      <Column Name="TerritoryID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TerritoryTanimi" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BolgeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Bolgeler_PersonelBolgeler" Member="PersonelBolgelers" ThisKey="TerritoryID" OtherKey="TerritoryID" Type="PersonelBolgeler" />
      <Association Name="Bolge_Bolgeler" Member="Bolge" ThisKey="BolgeID" OtherKey="BolgeID" Type="Bolge" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kategoriler" Member="Kategorilers">
    <Type Name="Kategoriler">
      <Column Name="KategoriID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KategoriAdi" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Tanimi" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Resim" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Kategoriler_Urunler" Member="Urunlers" ThisKey="KategoriID" OtherKey="KategoriID" Type="Urunler" />
    </Type>
  </Table>
  <Table Name="dbo.MusteriDemographics" Member="MusteriDemographics">
    <Type Name="MusteriDemographic">
      <Column Name="MusteriTypeID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MusteriDesc" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="MusteriDemographic_MusteriMusteriDemo" Member="MusteriMusteriDemos" ThisKey="MusteriTypeID" OtherKey="MusteriTypeID" Type="MusteriMusteriDemo" />
    </Type>
  </Table>
  <Table Name="dbo.Musteriler" Member="Musterilers">
    <Type Name="Musteriler">
      <Column Name="MusteriID" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SirketAdi" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="MusteriAdi" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MusteriUnvani" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Adres" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Sehir" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Bolge" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostaKodu" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ulke" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Telefon" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Faks" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Association Name="Musteriler_MusteriMusteriDemo" Member="MusteriMusteriDemos" ThisKey="MusteriID" OtherKey="MusteriID" Type="MusteriMusteriDemo" />
      <Association Name="Musteriler_Satislar" Member="Satislars" ThisKey="MusteriID" OtherKey="MusteriID" Type="Satislar" />
    </Type>
  </Table>
  <Table Name="dbo.MusteriMusteriDemo" Member="MusteriMusteriDemos">
    <Type Name="MusteriMusteriDemo">
      <Column Name="MusteriID" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MusteriTypeID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="MusteriDemographic_MusteriMusteriDemo" Member="MusteriDemographic" ThisKey="MusteriTypeID" OtherKey="MusteriTypeID" Type="MusteriDemographic" IsForeignKey="true" />
      <Association Name="Musteriler_MusteriMusteriDemo" Member="Musteriler" ThisKey="MusteriID" OtherKey="MusteriID" Type="Musteriler" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Nakliyeciler" Member="Nakliyecilers">
    <Type Name="Nakliyeciler">
      <Column Name="NakliyeciID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SirketAdi" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Telefon" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Association Name="Nakliyeciler_Satislar" Member="Satislars" ThisKey="NakliyeciID" OtherKey="ShipVia" Type="Satislar" />
    </Type>
  </Table>
  <Table Name="dbo.PersonelBolgeler" Member="PersonelBolgelers">
    <Type Name="PersonelBolgeler">
      <Column Name="PersonelID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TerritoryID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Bolgeler_PersonelBolgeler" Member="Bolgeler" ThisKey="TerritoryID" OtherKey="TerritoryID" Type="Bolgeler" IsForeignKey="true" />
      <Association Name="Personeller_PersonelBolgeler" Member="Personeller" ThisKey="PersonelID" OtherKey="PersonelID" Type="Personeller" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Personeller" Member="Personellers">
    <Type Name="Personeller">
      <Column Name="PersonelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoyAdi" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Adi" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Unvan" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UnvanEki" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="DogumTarihi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IseBaslamaTarihi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Adres" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Sehir" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Bolge" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostaKodu" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ulke" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="EvTelefonu" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Extension" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Fotograf" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Notlar" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BagliCalistigiKisi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FotografPath" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Personeller_PersonelBolgeler" Member="PersonelBolgelers" ThisKey="PersonelID" OtherKey="PersonelID" Type="PersonelBolgeler" />
      <Association Name="Personeller_Personeller" Member="Personellers" ThisKey="PersonelID" OtherKey="BagliCalistigiKisi" Type="Personeller" />
      <Association Name="Personeller_Satislar" Member="Satislars" ThisKey="PersonelID" OtherKey="PersonelID" Type="Satislar" />
      <Association Name="Personeller_Personeller" Member="Personeller1" ThisKey="BagliCalistigiKisi" OtherKey="PersonelID" Type="Personeller" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SatisDetay" Member="SatisDetays">
    <Type Name="SatisDetay">
      <Column Name="SatisID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UrunID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fiyat" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Adet" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Indirim" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Urunler_SatisDetay" Member="Urunler" ThisKey="UrunID" OtherKey="UrunID" Type="Urunler" IsForeignKey="true" />
      <Association Name="Satislar_SatisDetay" Member="Satislar" ThisKey="SatisID" OtherKey="SatisID" Type="Satislar" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Satislar" Member="Satislars">
    <Type Name="Satislar">
      <Column Name="SatisID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MusteriID" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="PersonelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SatisTarihi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OdemeTarihi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SevkTarihi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShipVia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NakliyeUcreti" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SevkAdi" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="SevkAdresi" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="SevkSehri" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="SevkBolgesi" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="SevkPostaKodu" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SevkUlkesi" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="Satislar_SatisDetay" Member="SatisDetays" ThisKey="SatisID" OtherKey="SatisID" Type="SatisDetay" />
      <Association Name="Musteriler_Satislar" Member="Musteriler" ThisKey="MusteriID" OtherKey="MusteriID" Type="Musteriler" IsForeignKey="true" />
      <Association Name="Nakliyeciler_Satislar" Member="Nakliyeciler" ThisKey="ShipVia" OtherKey="NakliyeciID" Type="Nakliyeciler" IsForeignKey="true" />
      <Association Name="Personeller_Satislar" Member="Personeller" ThisKey="PersonelID" OtherKey="PersonelID" Type="Personeller" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tedarikciler" Member="Tedarikcilers">
    <Type Name="Tedarikciler">
      <Column Name="TedarikciID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SirketAdi" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="MusteriAdi" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MusteriUnvani" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Adres" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Sehir" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Bolge" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostaKodu" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ulke" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Telefon" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Faks" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="WebSayfasi" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Tedarikciler_Urunler" Member="Urunlers" ThisKey="TedarikciID" OtherKey="TedarikciID" Type="Urunler" />
    </Type>
  </Table>
</Database>