//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuzeyRuzgari.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errors
    {
        public int ErrorId { get; set; }
        public string Reasonn { get; set; }
        public Nullable<int> Code { get; set; }
    }
}
